version: "3.9"

services:
  db:
    image: mysql:5.7
    #network_mode: host
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: SecretPassword

  sla-be:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    image: sla-be:latest
    #network_mode: host
    ports:
      - "8080:8080"
    links:
      - db
    restart: always
    environment:
      DB_HOST: db

  sla-fe:
    depends_on:
      - sla-be
    build:
      context: ui/
      dockerfile: Dockerfile
    image: sla-fe:latest
    ports:
      - "80:80"
    links:
      - sla-be
    restart: always
    environment:
      API_URL: sla-be         

volumes:
  db_data: {}
