version: "3.9"

networks:
  bridge:
    # driver: bridge
        
services:
  db:
    image: mysql:5.7
    network_mode: host
    # ports:
    #   - "3306:3306"    
    # networks:
    #   - bridge            
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: SecretPassword
    
  sla-api:
    depends_on:
      - db
    image: sla-api:latest
    network_mode: host
    # ports:
    #   - "8080:8080"
    # networks:
    #   - bridge      
    restart: always
    environment:
      WORDPRESS_DB_HOST: host.docker.internal

volumes:
  db_data: {}
